version: 2

builds:
  - id: espotad
    main: ./cmd/espotad
    env:
      - CGO_ENABLED=0
    binary: bin/{{ .ProjectName }}
    ldflags:
      - -s -w
      - -X github.com/prometheus/common/version.Version={{ .Version }}
      - -X github.com/prometheus/common/version.Revision={{ .Commit }}
      - -X github.com/prometheus/common/version.Branch={{ .Branch }}
      - -X github.com/prometheus/common/version.BuildDate={{ .Date }}
    targets:
      - linux_amd64
      - linux_arm_7
      - linux_arm64

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_sha512-checksums.txt"
  algorithm: sha512

archives:
  - id: tar
    formats:
      - tar.gz
    files:
      - LICENSE
      - README.md
